using System.Configuration;

namespace SmartHelper
{
    public enum MenuGroups
    {

        DashBoard = 1,
        Clients,
        Accounting,
        Settings,
        Administration,

        //
        Menu = 9998,
        Developer_Menu = 999,
    }
    public enum DaysOfTheWeek
    {
        Sunday = 1,
        Monday,
        Tuesday,
        Wednesday,
        Thursday,
        Friday,
        Saturday
    }
    public enum DatabaseAction
    {
        Remove = 1,
        Deactivate,
        Reactivate,
        Open,
        Close,
        IsDefault
    }
    public enum EmailStatus
    {
        Pending, // has been generated by the System
        DelayedSending,// attempted but failed
        Sent// sent
    }
    public enum MessageDisplayType
    {
        Success = 1,
        Warning,
        Error
    }

    public enum SettingType
    {
        BackEnd = 1,
        Portal = 2,
        All = 3,
        Email = 4
    }
    public enum VariableType
    {
        Boolean = 1,
        String = 2,
        Long = 3,
        Integer = 4,
        Double = 5,
        Decimal,
        Date_Time,
        Password,
        Percentage

    }
    public enum TransactionType
    {
        Payment = 1,
        Reversal,
        Refund,
        Void,
        Discount
    }

    public enum AccountType
    {
        Savings = 1,
        Cheque,
        Credit,
        Cash,

    }

    public enum CurrencyList

    {

        AED = 1
, AFN
, ALL
, AMD
, ANG
, AOA
, ARS
, AUD
, AWG
, AZN
, BAM
, BBD
, BDT
, BGN
, BHD
, BIF
, BMD
, BND
, BOB
, BRL
, BSD
, BTN
, BWP
, BYN
, BZD
, CAD
, CDF
, CHF
, CLP
, CNY
, COP
, CRC
, CUC
, CUP
, CVE
, CZK
, DJF
, DKK
, DOP
, DZD
, EGP
, ERN
, ETB
, EUR
, FJD
, FKP
, GBP
, GEL
, GGP
, GHS
, GIP
, GMD
, GNF
, GTQ
, GYD
, HKD
, HNL
, HRK
, HTG
, HUF
, IDR
, ILS
, IMP
, INR
, IQD
, IRR
, ISK
, JEP
, JMD
, JOD
, JPY
, KES
, KGS
, KHR
, KMF
, KPW
, KRW
, KWD
, KYD
, KZT
, LAK
, LBP
, LKR
, LRD
, LSL
, LYD
, MAD
, MDL
, MGA
, MKD
, MMK
, MNT
, MOP
, MRU
, MUR
, MVR
, MWK
, MXN
, MYR
, MZN
, NAD
, NGN
, NIO
, NOK
, NPR
, NZD
, OMR
, PAB
, PEN
, PGK
, PHP
, PKR
, PLN
, PYG
, QAR
, RON
, RSD
, RUB
, RWF
, SAR
, SBD
, SCR
, SDG
, SEK
, SGD
, SHP
, SLL
, SOS
, SPL
, SRD
, STN
, SVC
, SYP
, SZL
, THB
, TJS
, TMT
, TND
, TOP
, TRY
, TTD
, TVD
, TWD
, TZS
, UAH
, UGX
, USD
, UYU
, UZS
, VEF
, VND
, VUV
, WST
, XAF
, XCD
, XDR
, XOF
, XPF
, YER
, ZAR
, ZMW
, ZWD



    }


    public enum CountryList

    {
        Afghanistan = 1
, Albania
, Algeria
, American_Samoa
, Andorra
, Angola
, Anguilla
, Antigua_Barbuda
, Argentina
, Armenia
, Aruba
, Australia
, Austria
, Azerbaijan
, Bahamas, _The
, Bahrain
, Bangladesh
, Barbados
, Belarus
, Belgium
, Belize
, Benin
, Bermuda
, Bhutan
, Bolivia
, Bosnia_Herzegovina
, Botswana
, Brazil
, British_Virgin_Is
, Brunei
, Bulgaria
, Burkina_Faso
, Burma
, Burundi
, Cambodia
, Cameroon
, Canada
, Cape_Verde
, Cayman_Islands
, Central_African_Rep
, Chad
, Chile
, China
, Colombia
, Comoros
, Congo_Dem_Rep
, Congo_Repub_of_the
, Cook_Islands
, Costa_Rica
, Cote_dIvoire
, Croatia
, Cuba
, Cyprus
, Czech_Republic
, Denmark
, Djibouti
, Dominica
, Dominican_Republic
, East_Timor
, Ecuador
, Egypt
, El_Salvador
, Equatorial_Guinea
, Eritrea
, Estonia
, Ethiopia
, Faroe_Islands
, Fiji
, Finland
, France
, French_Guiana
, French_Polynesia
, Gabon
, Gambia_The
, Gaza_Strip
, Georgia
, Germany
, Ghana
, Gibraltar
, Greece
, Greenland
, Grenada
, Guadeloupe
, Guam
, Guatemala
, Guernsey
, Guinea
, Guinea_Bissau
, Guyana
, Haiti
, Honduras
, Hong_Kong
, Hungary
, Iceland
, India
, Indonesia
, Iran
, Iraq
, Ireland
, Isle_of_Man
, Israel
, Italy
, Jamaica
, Japan
, Jersey
, Jordan
, Kazakhstan
, Kenya
, Kiribati
, Korea_North
, Korea_South
, Kuwait
, Kyrgyzstan
, Laos
, Latvia
, Lebanon
, Lesotho
, Liberia
, Libya
, Liechtenstein
, Lithuania
, Luxembourg
, Macau
, Macedonia
, Madagascar
, Malawi
, Malaysia
, Maldives
, Mali
, Malta
, Marshall_Islands
, Martinique
, Mauritania
, Mauritius
, Mayotte
, Mexico
, Micronesia_Fed_St
, Moldova
, Monaco
, Mongolia
, Montserrat
, Morocco
, Mozambique
, Namibia
, Nauru
, Nepal
, Netherlands
, Netherlands_Antilles
, New_Caledonia
, New_Zealand
, Nicaragua
, Niger
, Nigeria
, N_Mariana_Islands
, Norway
, Oman
, Pakistan
, Palau
, Panama
, Papua_New_Guinea
, Paraguay
, Peru
, Philippines
, Poland
, Portugal
, Puerto_Rico
, Qatar
, Reunion
, Romania
, Russia
, Rwanda
, Saint_Helena
, Saint_Kitts_Nevis
, Saint_Lucia
, St_Pierre_Miquelon
, Saint_Vincent_and_the_Grenadines
, Samoa
, San_Marino
, Sao_Tome_Principe
, Saudi_Arabia
, Senegal
, Serbia
, Seychelles
, Sierra_Leone
, Singapore
, Slovakia
, Slovenia
, Solomon_Islands
, Somalia
, South_Africa
, Spain
, Sri_Lanka
, Sudan
, Suriname
, Swaziland
, Sweden
, Switzerland
, Syria
, Taiwan
, Tajikistan
, Tanzania
, Thailand
, Togo
, Tonga
, Trinidad_Tobago
, Tunisia
, Turkey
, Turkmenistan
, Turks_Caicos_Is
, Tuvalu
, Uganda
, Ukraine
, United_Arab_Emirates
, United_Kingdom
, United_States
, Uruguay
, Uzbekistan
, Vanuatu
, Venezuela
, Vietnam
, Virgin_Islands
, Wallis_Futuna
, West_Bank
, Western_Sahara
, Yemen
, Zambia
, Zimbabwe
    }
    public enum FeatureFlagList
    {
        Send_Email_On_Error = 1,
        CC_Client_On_Error,
        Enable_Document_Emailing_Functionality
    }
    public enum DocumentFormatList
    {
        pdf = 1,
        doc,
        xlsx,
        txt,
        rtf,
        ppt
    }

    public enum DocumentTypeList
    {
        Assignment = 1,
        Birth_Certificate,
        Proof_Of_Address
    }

    public enum EmailTypeList
    {
        Client_Statement = 1,
        Proof_Of_Payment,
        Invoice,

    }
    public enum AppSetting
    {
        Application_Name = 1,
        System_Version,
        Minimum_Year,
        BroadCast_Messages,
        Show_Custom_Exceptions_To_Users,
        Account_Number_Length,
        Date_Format,
        Mail_SMTP_Port,
        Mail_SMTP_Host,
        Mail_Enable_SSL,
        Mail_Use_Default_Credentials,
        Mail_Credential_User_Name,
        Mail_Credential_Password,
        Mail_Display_Name,
        VAT_Percentage,
        File_Maximum_UpLoadable_Size,
        Account_Number_Prefix,
        Application_Name_Prefix,
        Report_Footer_1,
        Report_Footer_2,
        Report_Logo_Path,
        Report_FootNotes,
        Capture_VAT_Inclusive_Payments,
        Default_Company_ID,
        Mail_Default_Subject,
        Statement_Save_To_Folder,
        Statement_Save_To_Physical_Location,
        Statement_Password_Protect,
        Statement_Password_For_Admin,
        Statement_Hide_Table_Boarders,
        Password_Reset_Pin_Code_Length,
        Password_Reset_Pin_Validity,
        Site_URL,
        Site_Reset_Password_URL,
        Site_Customer_Service_Email,
        Site_Customer_Service_Number


    }
    public enum TypeOfUser
    {
        Administrator = 1,
        Employer,
        Client,
        Visitor,
    }
    public enum Frequency
    {
        Weekly = 1,
        Monthly,
        Quaterly,
        Bi_Annually,
        Yearly
    }
    public enum PaymentState
    {
        Paid = 1,
        Reversed,
        Pending,
        Refunded,
        Discounted
    }
    public enum Permissions
    {  //User Module
        Add_User = 1,
        Update_User = 2,
        Activate_User,
        Deactivate_User,
        Delete_User,
        View_User,
        Change_User_Password,

        // Client Module
        Add_Client,
        Update_Client,
        Activate_Client,
        Deactivate_Client,
        Delete_Client,
        View_Client,
        Change_Client_Password,

        // Role Module
        Add_Role,
        Update_Role,
        Activate_Role,
        Deactivate_Role,
        Delete_Role,
        View_Role,

        // Product Module
        Add_Product,
        Update_Product,
        Activate_Product,
        Deactivate_Product,
        Delete_Product,
        View_Product,


        // Department Module
        Add_Department,
        Update_Department,
        Activate_Department,
        Deactivate_Department,
        Delete_Department,
        View_Department,

        // Enquiries Module
        Respond_To_Enquiry,
        Route_Enquiry,
        Suspend_Enquiry,
        Close_Enquiry,


        // Payment/Transactions
        Capture_Payment,
        Refund_Payment,
        Reverse_Payment,
        Void_Payment,


        // Menus
        Add_Menu,
        Update_Menu,
        Activate_Menu,
        Deactivate_Menu,
        Delete_Menu,
        View_Menu,


        // Course
        Add_Course,
        Update_Course,
        Delete_Course,
        View_Course,

        // Custom Setting
        Update_Custom_Setting,
        View_Custom_Setting,


        // Document Types
        Add_Document_Type,
        Update_Document_Type,
        Delete_Document_Type,
        View_Document_Type,

       

    }

    public enum QueryType
    {
        Sales = 1,
        Technical = 2,
        Other = 3,
    }
   
    public enum ContactTypeValues
    {
        Residential_Address = 1,
        Postal_Address = 2,
        Email_Address = 3,
        Cell_Phone = 4,
        Telephone
    }
    public enum AuditActionEnum
    {
        Logged_In,
        Logged_Out,
        Locked_Out,
        Password_Reset_Request,
        Removed_Permission
    }
    public enum ExceptionType
    {
        Logged_In,
        Logged_Out,
        Locked_Out,
        Password_Reset_Request,
    }
    public enum TaskRunType
    {
        Daily = 1,
        Weekly = 2,
        FortNight = 3,
        Monthly = 4,
        Quaterly = 5,
        Bi_Annualy = 6,
        Annualy = 7,
    }
    public enum ErrorSource
    {
        Web = 1,
        Database = 2,
        Web_Portal = 3,
        Task_Scheduler = 4,
        Email_Scheduler = 5
    }
    public enum AttachmentType
    {
        ProfilePicture = 1,
        Logo = 2,
        Document = 3
    }
    public enum GenderOrientation
    {
        Female = 1,
        Male = 2
    }
    public enum TaskRunStatus
    {
        New = 1,
        In_Queue = 2,
        In_Progress = 3,
        Completed = 4
    }

    public enum EmailTemplatesTypes
    {
        New_UserCreated = 1,
        Approval_Request = 2

    }

    public enum Priority
    {
        Critical = 1,
        High = 2,
        Medium = 3,
        Low = 4,
    }
}

