//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHelper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmartHelper {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmartHelper() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHelper.SmartHelper", typeof(SmartHelper).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string ADMIN {
            get {
                return ResourceManager.GetString("ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=WAKWACHIRENJE\WEKWACHIRENJE;Database=SSProd;.
        /// </summary>
        internal static string CONNECTIONSTRING {
            get {
                return ResourceManager.GetString("CONNECTIONSTRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q2gxcmVuamU2Mjk5IyM.
        /// </summary>
        internal static string CREDENTIALPASSWORD {
            get {
                return ResourceManager.GetString("CREDENTIALPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carochire@gmail.com.
        /// </summary>
        internal static string CREDENTIALUSERNAME {
            get {
                return ResourceManager.GetString("CREDENTIALUSERNAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Operation Failed.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string ENABLESSL {
            get {
                return ResourceManager.GetString("ENABLESSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to caroline9uzpgzl88.
        /// </summary>
        internal static string ENCYPTKEY {
            get {
                return ResourceManager.GetString("ENCYPTKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops Something Went Wrong!.
        /// </summary>
        internal static string GENERICERROR {
            get {
                return ResourceManager.GetString("GENERICERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string GENERICSUCCESS {
            get {
                return ResourceManager.GetString("GENERICSUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0},\n\n  Your account has been successfully created on the  {1}.Please log in using the password  &lt;b&gt;{2}&lt;/b&gt;.ReClient to keep your password  in a safe place alway. \n\n\n Kind Regards,\n\nGym Admin.
        /// </summary>
        internal static string PASSWORDGENERATED {
            get {
                return ResourceManager.GetString("PASSWORDGENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Operation Failed.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smtp.gmail.com.
        /// </summary>
        internal static string SMTPHOST {
            get {
                return ResourceManager.GetString("SMTPHOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 587.
        /// </summary>
        internal static string SMTPPORT {
            get {
                return ResourceManager.GetString("SMTPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string USEDEFAULTCREDENTIALS {
            get {
                return ResourceManager.GetString("USEDEFAULTCREDENTIALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Login, User is InActive!.
        /// </summary>
        internal static string USERINACTIVE {
            get {
                return ResourceManager.GetString("USERINACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Login Credentials.
        /// </summary>
        internal static string USERLOGIN {
            get {
                return ResourceManager.GetString("USERLOGIN", resourceCulture);
            }
        }
    }
}
